### ISSUE TITLE
hello! I don't see a place to put issues with the CovBat Repo!

### ISSUE THREAD

**Issue by ljollans** [andy1764/andy1764.github.io#1]
So I will leave my minor little bugs here:
in test.py you forgot to import sys and the file r-covbat.txt is not included in the repo as far as i can see.
thanks!

**Comment by andy1764** [comment]
Just added an issues section, thanks for pointing that out! As for r-covbat.txt, it's a somewhat large file so please run the script R-test.R, which generates r-covbat.txt, r-combat.txt, and the bladderbatch data.
